### PR TITLE
Integration

### PR DESCRIPTION
**Pull request by johncarl81**
Updates to the latest Asciidoclet version.

This PR may need a bit of an invasive merge as it includes a rebase.

### CODE REVIEW

**Comment by mojavelinux** [comment]
I've reworked this pull request into the original one I sent by squashing it down to two commits, my original one and your update.

https://github.com/asciidoctor/asciidoctor-java-integration/pull/35

**Comment by johncarl81** [comment]
:+1:

**Comment by jnorthr** [comment]
any chance of a few lines of examples on how to use this baby ?

**Comment by johncarl81** [comment]
@jnorthr check out the asciidoclet page: https://github.com/asciidoctor/asciidoclet or this blog article: http://asciidoctor.org/news/2013/06/03/asciidoclet-announcement/

**Comment by jnorthr** [comment]
ah, yes. Thx for that link John - just what i need to clarify my understanding of this beauty -
more soon
thx

**Pull request closed without merging**
